
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
namespace: webco
patches:
- patch: '[{"op": "replace", "path": "/metadata/name", "value": "wecolor2"}]'
  target:
    kind: Namespace
