apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: app-name
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-name
    spec:
      containers:
      - name: app
        image: app-image-repo
        ports:
        - name: app-port
          containerPort: 3000   
      nodeSelector:
        nodegroup: applications
      restartPolicy: Always
