apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: app-name
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-name
    spec:
      containers:
      - name: app
        image: app-image-repo
        ports:
        - name: app-port
          containerPort: 3000
        startupProbe:
          httpGet:
            path: /healthcheck
            port: app-port
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: app-port
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: app-port
          initialDelaySeconds: 5
          periodSeconds: 15    
      nodeSelector:
        nodegroup: applications
      restartPolicy: Always
